export const ADMIN_ACCESS_KEYS = [
  'products',
  'product_pricing',
  'categories',
  'vendors',
  'brands',
  'attributes',
  'specifications',
  'orders',
  'customers',
  'partners',
  'banners',
  'cashback_rules',
  'notes',
  'concepts',
  'archived',
  'analytics',
  'settings',
  'admins',
  'catalog_requests',
  'product_form_basic',
  'product_form_attributes',
  'product_form_specifications',
  'product_form_stock',
  'product_form_weight_dimensions',
  'product_form_media',
  'product_form_attachments',
] as const;

export type AdminAccessKey = (typeof ADMIN_ACCESS_KEYS)[number];
export type AdminAccess = Record<AdminAccessKey, boolean>;

export const PRODUCT_FORM_ACCESS_KEYS = [
  'product_form_basic',
  'product_form_attributes',
  'product_form_specifications',
  'product_form_stock',
  'product_pricing',
  'product_form_weight_dimensions',
  'product_form_media',
  'product_form_attachments',
] as const;

export type ProductFormAccessKey = (typeof PRODUCT_FORM_ACCESS_KEYS)[number];

const ALL_PRODUCT_FORM_STEPS_ON = {
  product_form_basic: true,
  product_form_attributes: true,
  product_form_specifications: true,
  product_form_stock: true,
  product_form_weight_dimensions: true,
  product_form_media: true,
  product_form_attachments: true,
} as const;

export const DEFAULT_ADMIN_ACCESS: AdminAccess = {
  products: true,
  product_pricing: true,
  categories: true,
  vendors: true,
  brands: true,
  attributes: true,
  specifications: true,
  orders: true,
  customers: true,
  partners: true,
  banners: true,
  cashback_rules: true,
  notes: true,
  concepts: true,
  archived: true,
  analytics: true,
  settings: true,
  admins: true,
  catalog_requests: true,
  ...ALL_PRODUCT_FORM_STEPS_ON,
};

export const DEFAULT_CATALOG_MANAGER_ACCESS: AdminAccess = {
  products: true,
  product_pricing: false,
  categories: true,
  vendors: true,
  brands: true,
  attributes: true,
  specifications: true,
  orders: false,
  customers: false,
  partners: false,
  banners: false,
  cashback_rules: false,
  notes: false,
  concepts: true,
  archived: false,
  analytics: false,
  settings: false,
  admins: false,
  catalog_requests: true,
  ...ALL_PRODUCT_FORM_STEPS_ON,
};

export const DEFAULT_VENDOR_PORTAL_ACCESS: AdminAccess = {
  products: true,
  product_pricing: true,
  categories: false,
  vendors: false,
  brands: false,
  attributes: false,
  specifications: false,
  orders: false,
  customers: false,
  partners: false,
  banners: false,
  cashback_rules: false,
  notes: false,
  concepts: false,
  archived: false,
  analytics: false,
  settings: false,
  admins: false,
  catalog_requests: false,
  product_form_basic: true,
  product_form_attributes: false,
  product_form_specifications: false,
  product_form_stock: false,
  product_form_weight_dimensions: false,
  product_form_media: true,
  product_form_attachments: false,
};
